name: dio_service
description: A dart project that provides a wrapper class around Dio that adds a single instance with useful interceptors.
version: 1.1.0-dev.11
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  # analyzer
  dart_code_metrics: ^4.17.0
  dio: ^4.0.6

  flutter:
    sdk: flutter

  fpdart: ^0.3.0
  humanizer: ^2.0.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: "^3.0.1"
